/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Education {
  'field' : string,
  'startYear' : string,
  'endYear' : string,
  'institution' : string,
  'degree' : string,
}
export interface PersonalInfo {
  'bio' : string,
  'title' : string,
  'name' : string,
  'email' : string,
  'website' : string,
  'phone' : string,
}
export type Plan = { 'pro' : null } |
  { 'free' : null };
export interface PortfolioDTO {
  'resume' : Resume,
  'credits' : bigint,
  'username' : string,
  'isPublished' : boolean,
  'displayName' : string,
  'owner' : Principal,
  'plan' : Plan,
  'lastUpdated' : Time,
}
export interface PortfolioInput {
  'username' : string,
  'displayName' : string,
  'projects' : Array<Project>,
  'education' : Array<Education>,
  'work' : Array<WorkExperience>,
  'personal' : PersonalInfo,
  'skills' : Array<string>,
}
export interface Project {
  'url' : string,
  'name' : string,
  'description' : string,
}
export interface Resume {
  'projects' : Array<Project>,
  'education' : Array<Education>,
  'work' : Array<WorkExperience>,
  'lastUpdated' : Time,
  'personal' : PersonalInfo,
  'skills' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkExperience {
  'endDate' : string,
  'role' : string,
  'description' : string,
  'company' : string,
  'startDate' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSkills' : ActorMethod<[Array<string>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPortfolios' : ActorMethod<[], Array<PortfolioDTO>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPortfolio' : ActorMethod<[], [] | [PortfolioDTO]>,
  'getPortfolio' : ActorMethod<[Principal], PortfolioDTO>,
  'getPublishedPortfolios' : ActorMethod<[], Array<PortfolioDTO>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeSkill' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePortfolio' : ActorMethod<[PortfolioInput], PortfolioDTO>,
  'setPublished' : ActorMethod<[boolean], PortfolioDTO>,
  'setUserPlan' : ActorMethod<[Principal, Plan], undefined>,
  'upgradeToPro' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];