/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Project = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Education = IDL.Record({
  'field' : IDL.Text,
  'startYear' : IDL.Text,
  'endYear' : IDL.Text,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'endDate' : IDL.Text,
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Time = IDL.Int;
export const PersonalInfo = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'phone' : IDL.Text,
});
export const Resume = IDL.Record({
  'projects' : IDL.Vec(Project),
  'education' : IDL.Vec(Education),
  'work' : IDL.Vec(WorkExperience),
  'lastUpdated' : Time,
  'personal' : PersonalInfo,
  'skills' : IDL.Vec(IDL.Text),
});
export const Plan = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
export const PortfolioDTO = IDL.Record({
  'resume' : Resume,
  'credits' : IDL.Nat,
  'username' : IDL.Text,
  'isPublished' : IDL.Bool,
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'plan' : Plan,
  'lastUpdated' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});
export const PortfolioInput = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'education' : IDL.Vec(Education),
  'work' : IDL.Vec(WorkExperience),
  'personal' : PersonalInfo,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPortfolios' : IDL.Func([], [IDL.Vec(PortfolioDTO)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPortfolio' : IDL.Func([], [IDL.Opt(PortfolioDTO)], ['query']),
  'getPortfolio' : IDL.Func([IDL.Principal], [PortfolioDTO], ['query']),
  'getPublishedPortfolios' : IDL.Func([], [IDL.Vec(PortfolioDTO)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSkill' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePortfolio' : IDL.Func([PortfolioInput], [PortfolioDTO], []),
  'setPublished' : IDL.Func([IDL.Bool], [PortfolioDTO], []),
  'setUserPlan' : IDL.Func([IDL.Principal, Plan], [], []),
  'upgradeToPro' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Project = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Education = IDL.Record({
    'field' : IDL.Text,
    'startYear' : IDL.Text,
    'endYear' : IDL.Text,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'endDate' : IDL.Text,
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Time = IDL.Int;
  const PersonalInfo = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Resume = IDL.Record({
    'projects' : IDL.Vec(Project),
    'education' : IDL.Vec(Education),
    'work' : IDL.Vec(WorkExperience),
    'lastUpdated' : Time,
    'personal' : PersonalInfo,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Plan = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const PortfolioDTO = IDL.Record({
    'resume' : Resume,
    'credits' : IDL.Nat,
    'username' : IDL.Text,
    'isPublished' : IDL.Bool,
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'plan' : Plan,
    'lastUpdated' : Time,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const PortfolioInput = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'education' : IDL.Vec(Education),
    'work' : IDL.Vec(WorkExperience),
    'personal' : PersonalInfo,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPortfolios' : IDL.Func([], [IDL.Vec(PortfolioDTO)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPortfolio' : IDL.Func([], [IDL.Opt(PortfolioDTO)], ['query']),
    'getPortfolio' : IDL.Func([IDL.Principal], [PortfolioDTO], ['query']),
    'getPublishedPortfolios' : IDL.Func([], [IDL.Vec(PortfolioDTO)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSkill' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePortfolio' : IDL.Func([PortfolioInput], [PortfolioDTO], []),
    'setPublished' : IDL.Func([IDL.Bool], [PortfolioDTO], []),
    'setUserPlan' : IDL.Func([IDL.Principal, Plan], [], []),
    'upgradeToPro' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };