/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PortfolioDTO {
    resume: Resume;
    credits: bigint;
    username: string;
    isPublished: boolean;
    displayName: string;
    owner: Principal;
    plan: Plan;
    lastUpdated: Time;
}
export interface WorkExperience {
    endDate: string;
    role: string;
    description: string;
    company: string;
    startDate: string;
}
export interface Education {
    field: string;
    startYear: string;
    endYear: string;
    institution: string;
    degree: string;
}
export interface PersonalInfo {
    bio: string;
    title: string;
    name: string;
    email: string;
    website: string;
    phone: string;
}
export interface Resume {
    projects: Array<Project>;
    education: Array<Education>;
    work: Array<WorkExperience>;
    lastUpdated: Time;
    personal: PersonalInfo;
    skills: Array<string>;
}
export interface Project {
    url: string;
    name: string;
    description: string;
}
export interface PortfolioInput {
    username: string;
    displayName: string;
    projects: Array<Project>;
    education: Array<Education>;
    work: Array<WorkExperience>;
    personal: PersonalInfo;
    skills: Array<string>;
}
export interface UserProfile {
    username: string;
    displayName: string;
}
export enum Plan {
    pro = "pro",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSkills(skills: Array<string>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPortfolios(): Promise<Array<PortfolioDTO>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyPortfolio(): Promise<PortfolioDTO | null>;
    getPortfolio(user: Principal): Promise<PortfolioDTO>;
    getPublishedPortfolios(): Promise<Array<PortfolioDTO>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeSkill(skill: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePortfolio(input: PortfolioInput): Promise<PortfolioDTO>;
    setPublished(isPublished: boolean): Promise<PortfolioDTO>;
    setUserPlan(user: Principal, plan: Plan): Promise<void>;
    upgradeToPro(): Promise<void>;
}
import type { Plan as _Plan, PortfolioDTO as _PortfolioDTO, Resume as _Resume, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSkills(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSkills(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllPortfolios(): Promise<Array<PortfolioDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPortfolios();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPortfolios();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPortfolio(): Promise<PortfolioDTO | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPortfolio();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPortfolio();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolio(arg0: Principal): Promise<PortfolioDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio(arg0);
                return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio(arg0);
            return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPortfolios(): Promise<Array<PortfolioDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPortfolios();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPortfolios();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeSkill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSkill(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePortfolio(arg0: PortfolioInput): Promise<PortfolioDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.savePortfolio(arg0);
                return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePortfolio(arg0);
            return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPublished(arg0: boolean): Promise<PortfolioDTO> {
        if (this.processError) {
            try {
                const result = await this.actor.setPublished(arg0);
                return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPublished(arg0);
            return from_candid_PortfolioDTO_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserPlan(arg0: Principal, arg1: Plan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPlan(arg0, to_candid_Plan_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPlan(arg0, to_candid_Plan_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upgradeToPro(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPro();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPro();
            return result;
        }
    }
}
function from_candid_Plan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plan): Plan {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioDTO_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioDTO): PortfolioDTO {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioDTO]): PortfolioDTO | null {
    return value.length === 0 ? null : from_candid_PortfolioDTO_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resume: _Resume;
    credits: bigint;
    username: string;
    isPublished: boolean;
    displayName: string;
    owner: Principal;
    plan: _Plan;
    lastUpdated: _Time;
}): {
    resume: Resume;
    credits: bigint;
    username: string;
    isPublished: boolean;
    displayName: string;
    owner: Principal;
    plan: Plan;
    lastUpdated: Time;
} {
    return {
        resume: value.resume,
        credits: value.credits,
        username: value.username,
        isPublished: value.isPublished,
        displayName: value.displayName,
        owner: value.owner,
        plan: from_candid_Plan_n6(_uploadFile, _downloadFile, value.plan),
        lastUpdated: value.lastUpdated
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
}): Plan {
    return "pro" in value ? Plan.pro : "free" in value ? Plan.free : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioDTO>): Array<PortfolioDTO> {
    return value.map((x)=>from_candid_PortfolioDTO_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Plan_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): _Plan {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): {
    pro: null;
} | {
    free: null;
} {
    return value == Plan.pro ? {
        pro: null
    } : value == Plan.free ? {
        free: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
